### PR TITLE
NP.VSTACK -> List

### PR DESCRIPTION
**Pull request by jinyul80**
Test time more fast.

### CODE REVIEW

**Comment by jinyul80** [comment]
# np.vstack (64.1 sec)
iNum = np.random.randn(25600)
xlist = np.empty(0).reshape(0, 25600)
for _ in range(1000):
    xlist = np.vstack((xlist, iNum))

# list (0.09 sec)
iNum = np.random.randn(25600)
xlist2 = []
for _ in range(1000):
    xlist2.append(iNum)
xlist2 = np.vstack(xlist2)

**Comment by hunkim** [comment]
Oh. Let's go with list. Thanks.

Sung

**Comment by kkweon** [comment]
I got a similar result (all measured in seconds, repeated 1000 times)
```text
vstack: 2.000067383
list  : 0.126377978
concat: 1.756322526
slice : 0.053241204
```

```python
import numpy as np
import timeit

np.random.seed(123)

ROUND = 100
DIM = 1024

RANDOM_NUMBER = np.random.randn(DIM)


def vstack():
    result = np.empty([0, DIM])

    for _ in range(ROUND):
        result = np.vstack([result, RANDOM_NUMBER])

    return result


def concat():
    result = np.empty([0, DIM])

    for _ in range(ROUND):
        result = np.concatenate([result, RANDOM_NUMBER.reshape(1, -1)])

    return result


def slice():
    result = np.zeros(shape=[ROUND, DIM])

    for i in range(ROUND):
        result[i] = RANDOM_NUMBER
    return result


def list_op():
    result = []

    for _ in range(ROUND):
        result.append(RANDOM_NUMBER)

    return np.vstack(result)


if __name__ == '__main__':
    a1 = timeit.timeit("vstack()",
                       setup="from __main__ import vstack",
                       number=1000)

    a2 = timeit.timeit("list_op()",
                       setup="from __main__ import list_op",
                       number=1000)

    a3 = timeit.timeit("concat()",
                       setup="from __main__ import concat",
                       number=1000)

    a4 = timeit.timeit("slice()",
                       setup="from __main__ import slice",
                       number=1000)

    print("vstack: {:>10.9f}".format(a1))
    print("list  : {:>10.9f}".format(a2))
    print("concat: {:>10.9f}".format(a3))
    print("slice : {:>10.9f}".format(a4))

```

**Comment by hunkim** [comment]
Let's go for it!

**Pull request merged**
